trigger:
- master

pool: Default

steps: 
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: '-DStore="$Store"'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
