trigger:
- master

pool: Default

steps: 
- task: replacetokens@3
  inputs:
    targetFiles: '/Users/dejanadmin/_work/1/s/src/main/java/DriverInit.java'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true
  displayName: Perform variable substitution in java file

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
