parameters:
  - name: STORE
    displayName: STORE
    type: string
    default: android
    values:
      - iOS
      - android

trigger:
- master

pool: Default

steps: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      env:
      export STORE="${{parameters.STORE}}"
      echo "${{parameters.STORE}}"
      echo "$(pass)"
      echo (export STORE="${{parameters.STORE}}")
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
