trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      export Store = $(Store)
      export Device = $(Device)
      export udid = $(udid)
      export username = $(username)
      export pass = $(pass)
      export teamId = $(teamId)
      export OS = $(OS)
      export bundleId = $(bundleId)
      export appLocation = $(appLocation)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false