parameters:
  - name: STORE
    displayName: STORE
    type: string
    default: android
    values:
      - iOS
      - android

trigger:
- master

pool: Default

steps: 
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: '**\*.config'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
