trigger:
- master

pool: Default

steps: 
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Bash@3
  inputs:
    script: 
      export Store=$(Store)