trigger:
- master

pool: Default
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps: 
- script: echo '$(Build.BuildNumber)'
- task: replacetokens@3
  displayName: Perform variable substitution in java file
  inputs:
    targetFiles: '**\*.java'
    encoding: 'auto'
    writeBOM: false
    verbosity: 'detailed'
    actionOnMissing: 'warn'
    keepToken: true
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
