trigger:
- master

pool: Default

steps: 


- bash: |
    env:
      USERNAME:$(USERNAME)
      PASS:$(PASS)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test -DStore=$(Store)
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
