trigger:
- master

pool: Default
steps: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      export -Dusername=$(username)
      export -Dpass=$(pass)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test -DStore=$(Store)
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
