trigger:
- master

pool: Default

steps: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export Store="$(STORE)"
      export username="$(USERNAME)"
      export pass="$(PASS)"

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
