parameters:
  - name: Store
    displayName: Choose Store
    type: string
    default: iOS
    values:
      - iOS
      - android

trigger:
- master

pool: Default

steps: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      Store:$(parameters.Store)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
