trigger:
- master

pool: Default

steps: 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export USERNAME=$USERNAME
      export PASS=$PASS

- bash: |
    env:
      USERNAME:$(USERNAME)
      PASS:$(PASS)

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: clean test -DStore=$(Store)
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
